spring:
  datasource:
    url: jdbc:mysql://localhost:3306/travelq?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: root
    password: 9212
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  logging:
    level:
      org.springframework.core.env: DEBUG
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: your
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email
            client-name: kakao

          google:
            client-id: your
            client-secret: your
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            authorization-grant-type: authorization_code
            scope: profile, email
            client-name: google

          naver:
            client-id: your
            client-secret: your
            redirect-uri: "{baseUrl}/login/oauth2/code/naver"
            authorization-grant-type: authorization_code
            scope: name, email
            client-name: naver

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
jwt:
  secret: TheOnlyTrueWisdomIsInKnowingYouKnowNothing@42!

file:
  rcmDir: D:\TravelQ\TravelQ_back_end\src\main\resources\static\uploads\recommends
